// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v25.3
// source: vyse.proto

package vypb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─────────────────────────────────────────────────────────────────────────────
// InferenceRequest
// ─────────────────────────────────────────────────────────────────────────────

type InferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionIdHash  string `protobuf:"bytes,1,opt,name=session_id_hash,json=sessionIdHash,proto3" json:"session_id_hash,omitempty"`
	Prompt         string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ClientIpHash   string `protobuf:"bytes,3,opt,name=client_ip_hash,json=clientIpHash,proto3" json:"client_ip_hash,omitempty"`
	RequestId      string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	GatewayVersion string `protobuf:"bytes,5,opt,name=gateway_version,json=gatewayVersion,proto3" json:"gateway_version,omitempty"`
}

func (x *InferenceRequest) Reset()         { *x = InferenceRequest{} }
func (x *InferenceRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *InferenceRequest) ProtoMessage()  {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InferenceRequest) GetSessionIdHash() string {
	if x != nil {
		return x.SessionIdHash
	}
	return ""
}
func (x *InferenceRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}
func (x *InferenceRequest) GetClientIpHash() string {
	if x != nil {
		return x.ClientIpHash
	}
	return ""
}
func (x *InferenceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}
func (x *InferenceRequest) GetGatewayVersion() string {
	if x != nil {
		return x.GatewayVersion
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// InferenceResponse
// ─────────────────────────────────────────────────────────────────────────────

type InferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response       string          `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Tier           int32           `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	HybridScore    float32         `protobuf:"fixed32,3,opt,name=hybrid_score,json=hybridScore,proto3" json:"hybrid_score,omitempty"`
	DurationMins   float32         `protobuf:"fixed32,4,opt,name=duration_mins,json=durationMins,proto3" json:"duration_mins,omitempty"`
	RequestId      string          `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ScoreBreakdown *ScoreBreakdown `protobuf:"bytes,6,opt,name=score_breakdown,json=scoreBreakdown,proto3" json:"score_breakdown,omitempty"`
}

func (x *InferenceResponse) Reset()         { *x = InferenceResponse{} }
func (x *InferenceResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *InferenceResponse) ProtoMessage()  {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InferenceResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}
func (x *InferenceResponse) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}
func (x *InferenceResponse) GetHybridScore() float32 {
	if x != nil {
		return x.HybridScore
	}
	return 0
}
func (x *InferenceResponse) GetDurationMins() float32 {
	if x != nil {
		return x.DurationMins
	}
	return 0
}
func (x *InferenceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}
func (x *InferenceResponse) GetScoreBreakdown() *ScoreBreakdown {
	if x != nil {
		return x.ScoreBreakdown
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// ScoreBreakdown
// ─────────────────────────────────────────────────────────────────────────────

type ScoreBreakdown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VScore        float32 `protobuf:"fixed32,1,opt,name=v_score,json=vScore,proto3" json:"v_score,omitempty"`
	DScore        float32 `protobuf:"fixed32,2,opt,name=d_score,json=dScore,proto3" json:"d_score,omitempty"`
	EScore        float32 `protobuf:"fixed32,3,opt,name=e_score,json=eScore,proto3" json:"e_score,omitempty"`
	AScore        float32 `protobuf:"fixed32,4,opt,name=a_score,json=aScore,proto3" json:"a_score,omitempty"`
	IntentFlagged bool    `protobuf:"varint,5,opt,name=intent_flagged,json=intentFlagged,proto3" json:"intent_flagged,omitempty"`
	IntentLabel   string  `protobuf:"bytes,6,opt,name=intent_label,json=intentLabel,proto3" json:"intent_label,omitempty"`
}

func (x *ScoreBreakdown) Reset()         { *x = ScoreBreakdown{} }
func (x *ScoreBreakdown) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ScoreBreakdown) ProtoMessage()  {}

func (x *ScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScoreBreakdown) GetVScore() float32 {
	if x != nil {
		return x.VScore
	}
	return 0
}
func (x *ScoreBreakdown) GetDScore() float32 {
	if x != nil {
		return x.DScore
	}
	return 0
}
func (x *ScoreBreakdown) GetEScore() float32 {
	if x != nil {
		return x.EScore
	}
	return 0
}
func (x *ScoreBreakdown) GetAScore() float32 {
	if x != nil {
		return x.AScore
	}
	return 0
}
func (x *ScoreBreakdown) GetIntentFlagged() bool {
	if x != nil {
		return x.IntentFlagged
	}
	return false
}
func (x *ScoreBreakdown) GetIntentLabel() string {
	if x != nil {
		return x.IntentLabel
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// GetSessionRequest
// ─────────────────────────────────────────────────────────────────────────────

type GetSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionIdHash string `protobuf:"bytes,1,opt,name=session_id_hash,json=sessionIdHash,proto3" json:"session_id_hash,omitempty"`
}

func (x *GetSessionRequest) Reset()         { *x = GetSessionRequest{} }
func (x *GetSessionRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetSessionRequest) ProtoMessage()  {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSessionRequest) GetSessionIdHash() string {
	if x != nil {
		return x.SessionIdHash
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// ListSessionsRequest
// ─────────────────────────────────────────────────────────────────────────────

type ListSessionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TierFilter int32 `protobuf:"varint,1,opt,name=tier_filter,json=tierFilter,proto3" json:"tier_filter,omitempty"`
	Limit      int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListSessionsRequest) Reset()         { *x = ListSessionsRequest{} }
func (x *ListSessionsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ListSessionsRequest) ProtoMessage()  {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSessionsRequest) GetTierFilter() int32 {
	if x != nil {
		return x.TierFilter
	}
	return 0
}
func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ─────────────────────────────────────────────────────────────────────────────
// DeleteSessionRequest
// ─────────────────────────────────────────────────────────────────────────────

type DeleteSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionIdHash string `protobuf:"bytes,1,opt,name=session_id_hash,json=sessionIdHash,proto3" json:"session_id_hash,omitempty"`
}

func (x *DeleteSessionRequest) Reset()         { *x = DeleteSessionRequest{} }
func (x *DeleteSessionRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DeleteSessionRequest) ProtoMessage()  {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSessionRequest) GetSessionIdHash() string {
	if x != nil {
		return x.SessionIdHash
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// DeleteSessionResponse
// ─────────────────────────────────────────────────────────────────────────────

type DeleteSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteSessionResponse) Reset()         { *x = DeleteSessionResponse{} }
func (x *DeleteSessionResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DeleteSessionResponse) ProtoMessage()  {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}
func (x *DeleteSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─────────────────────────────────────────────────────────────────────────────
// SessionState
// ─────────────────────────────────────────────────────────────────────────────

type SessionState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionIdHash      string  `protobuf:"bytes,1,opt,name=session_id_hash,json=sessionIdHash,proto3" json:"session_id_hash,omitempty"`
	Tier               int32   `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
	FirstSeenAt        int64   `protobuf:"varint,3,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastActiveAt       int64   `protobuf:"varint,4,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	TrackingStartedAt  int64   `protobuf:"varint,5,opt,name=tracking_started_at,json=trackingStartedAt,proto3" json:"tracking_started_at,omitempty"`
	RequestCount       int64   `protobuf:"varint,6,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	DynamicMeanRpm     float32 `protobuf:"fixed32,7,opt,name=dynamic_mean_rpm,json=dynamicMeanRpm,proto3" json:"dynamic_mean_rpm,omitempty"`
	CurrentHybridScore float32 `protobuf:"fixed32,8,opt,name=current_hybrid_score,json=currentHybridScore,proto3" json:"current_hybrid_score,omitempty"`
	DurationMins       float32 `protobuf:"fixed32,9,opt,name=duration_mins,json=durationMins,proto3" json:"duration_mins,omitempty"`
	IsBanned           bool    `protobuf:"varint,10,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
}

func (x *SessionState) Reset()         { *x = SessionState{} }
func (x *SessionState) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SessionState) ProtoMessage()  {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionState) GetSessionIdHash() string {
	if x != nil {
		return x.SessionIdHash
	}
	return ""
}
func (x *SessionState) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}
func (x *SessionState) GetFirstSeenAt() int64 {
	if x != nil {
		return x.FirstSeenAt
	}
	return 0
}
func (x *SessionState) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}
func (x *SessionState) GetTrackingStartedAt() int64 {
	if x != nil {
		return x.TrackingStartedAt
	}
	return 0
}
func (x *SessionState) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}
func (x *SessionState) GetDynamicMeanRpm() float32 {
	if x != nil {
		return x.DynamicMeanRpm
	}
	return 0
}
func (x *SessionState) GetCurrentHybridScore() float32 {
	if x != nil {
		return x.CurrentHybridScore
	}
	return 0
}
func (x *SessionState) GetDurationMins() float32 {
	if x != nil {
		return x.DurationMins
	}
	return 0
}
func (x *SessionState) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

// ─────────────────────────────────────────────────────────────────────────────
// GetStatsRequest
// ─────────────────────────────────────────────────────────────────────────────

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsRequest) Reset()         { *x = GetStatsRequest{} }
func (x *GetStatsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *GetStatsRequest) ProtoMessage()  {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// ─────────────────────────────────────────────────────────────────────────────
// StatsResponse
// ─────────────────────────────────────────────────────────────────────────────

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSessions      int64 `protobuf:"varint,1,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	ActiveSessions     int64 `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	Tier1Count         int64 `protobuf:"varint,3,opt,name=tier1_count,json=tier1Count,proto3" json:"tier1_count,omitempty"`
	Tier2Count         int64 `protobuf:"varint,4,opt,name=tier2_count,json=tier2Count,proto3" json:"tier2_count,omitempty"`
	Tier3Count         int64 `protobuf:"varint,5,opt,name=tier3_count,json=tier3Count,proto3" json:"tier3_count,omitempty"`
	TotalRequests      int64 `protobuf:"varint,6,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	NoiseInjectedCount int64 `protobuf:"varint,7,opt,name=noise_injected_count,json=noiseInjectedCount,proto3" json:"noise_injected_count,omitempty"`
	RekorEntriesCount  int64 `protobuf:"varint,8,opt,name=rekor_entries_count,json=rekorEntriesCount,proto3" json:"rekor_entries_count,omitempty"`
}

func (x *StatsResponse) Reset()         { *x = StatsResponse{} }
func (x *StatsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *StatsResponse) ProtoMessage()  {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatsResponse) GetTotalSessions() int64 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}
func (x *StatsResponse) GetActiveSessions() int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}
func (x *StatsResponse) GetTier1Count() int64 {
	if x != nil {
		return x.Tier1Count
	}
	return 0
}
func (x *StatsResponse) GetTier2Count() int64 {
	if x != nil {
		return x.Tier2Count
	}
	return 0
}
func (x *StatsResponse) GetTier3Count() int64 {
	if x != nil {
		return x.Tier3Count
	}
	return 0
}
func (x *StatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}
func (x *StatsResponse) GetNoiseInjectedCount() int64 {
	if x != nil {
		return x.NoiseInjectedCount
	}
	return 0
}
func (x *StatsResponse) GetRekorEntriesCount() int64 {
	if x != nil {
		return x.RekorEntriesCount
	}
	return 0
}

// ─────────────────────────────────────────────────────────────────────────────
// HealthCheckRequest
// ─────────────────────────────────────────────────────────────────────────────

type HealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthCheckRequest) Reset()         { *x = HealthCheckRequest{} }
func (x *HealthCheckRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HealthCheckRequest) ProtoMessage()  {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// ─────────────────────────────────────────────────────────────────────────────
// HealthCheckResponse
// ─────────────────────────────────────────────────────────────────────────────

type HealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status            string  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version           string  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RedisConnected    bool    `protobuf:"varint,3,opt,name=redis_connected,json=redisConnected,proto3" json:"redis_connected,omitempty"`
	PostgresConnected bool    `protobuf:"varint,4,opt,name=postgres_connected,json=postgresConnected,proto3" json:"postgres_connected,omitempty"`
	RekorConnected    bool    `protobuf:"varint,5,opt,name=rekor_connected,json=rekorConnected,proto3" json:"rekor_connected,omitempty"`
	ModelsLoaded      bool    `protobuf:"varint,6,opt,name=models_loaded,json=modelsLoaded,proto3" json:"models_loaded,omitempty"`
	UptimeSeconds     float32 `protobuf:"fixed32,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
}

func (x *HealthCheckResponse) Reset()         { *x = HealthCheckResponse{} }
func (x *HealthCheckResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HealthCheckResponse) ProtoMessage()  {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vyse_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}
func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}
func (x *HealthCheckResponse) GetRedisConnected() bool {
	if x != nil {
		return x.RedisConnected
	}
	return false
}
func (x *HealthCheckResponse) GetPostgresConnected() bool {
	if x != nil {
		return x.PostgresConnected
	}
	return false
}
func (x *HealthCheckResponse) GetRekorConnected() bool {
	if x != nil {
		return x.RekorConnected
	}
	return false
}
func (x *HealthCheckResponse) GetModelsLoaded() bool {
	if x != nil {
		return x.ModelsLoaded
	}
	return false
}
func (x *HealthCheckResponse) GetUptimeSeconds() float32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// ─────────────────────────────────────────────────────────────────────────────
// File descriptor and init
// ─────────────────────────────────────────────────────────────────────────────

// Placeholder raw file descriptor — populated by the real protoc output.
// When running make proto-gen, protoc replaces this entire section with the
// actual binary-encoded file descriptor for vyse.proto.
var file_vyse_proto_rawDescOnce sync.Once
var file_vyse_proto_rawDescData []byte
var file_vyse_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vyse_proto_goTypes = []any{
	(*InferenceRequest)(nil),      // 0: vyse.v1.InferenceRequest
	(*InferenceResponse)(nil),     // 1: vyse.v1.InferenceResponse
	(*ScoreBreakdown)(nil),        // 2: vyse.v1.ScoreBreakdown
	(*GetSessionRequest)(nil),     // 3: vyse.v1.GetSessionRequest
	(*ListSessionsRequest)(nil),   // 4: vyse.v1.ListSessionsRequest
	(*DeleteSessionRequest)(nil),  // 5: vyse.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 6: vyse.v1.DeleteSessionResponse
	(*SessionState)(nil),          // 7: vyse.v1.SessionState
	(*GetStatsRequest)(nil),       // 8: vyse.v1.GetStatsRequest
	(*StatsResponse)(nil),         // 9: vyse.v1.StatsResponse
	(*HealthCheckRequest)(nil),    // 10: vyse.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 11: vyse.v1.HealthCheckResponse
}

// Ensure all imports are used.
var _ = protoreflect.EnumNumber(0)
var _ = protoimpl.EnforceVersion
var _ reflect.Type
var _ sync.Mutex

func init() {
	file_vyse_proto_rawDescOnce.Do(func() {
		// Real protoc output inserts the binary descriptor here.
		// Run `make proto-gen` in gateway/ to regenerate.
		file_vyse_proto_rawDescData = file_vyse_proto_rawDesc
	})
}

// file_vyse_proto_rawDesc is populated by protoc. This placeholder prevents
// compilation failure before make proto-gen is run.
// Replace this entire var block with the actual protoc output.
var file_vyse_proto_rawDesc = []byte{
	// Intentionally empty — replaced by make proto-gen.
	// The struct definitions above compile without the descriptor.
	// Full reflection, marshalling, and JSON support require running:
	//   cd gateway && make proto-gen
}
