// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v25.3
// source: vyse.proto

package vypb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ─────────────────────────────────────────────────────────────────────────────
// RPC method descriptors — referenced by client and server registration
// ─────────────────────────────────────────────────────────────────────────────

const (
	VyseEngine_Infer_FullMethodName         = "/vyse.v1.VyseEngine/Infer"
	VyseEngine_GetSession_FullMethodName    = "/vyse.v1.VyseEngine/GetSession"
	VyseEngine_ListSessions_FullMethodName  = "/vyse.v1.VyseEngine/ListSessions"
	VyseEngine_DeleteSession_FullMethodName = "/vyse.v1.VyseEngine/DeleteSession"
	VyseEngine_GetStats_FullMethodName      = "/vyse.v1.VyseEngine/GetStats"
	VyseEngine_HealthCheck_FullMethodName   = "/vyse.v1.VyseEngine/HealthCheck"
)

// ─────────────────────────────────────────────────────────────────────────────
// Client
// ─────────────────────────────────────────────────────────────────────────────

// VyseEngineClient is the client API for the VyseEngine service.
type VyseEngineClient interface {
	// Infer processes a single inference request through the full defence
	// pipeline: session state, scoring, tier classification, LLM call,
	// perturbation (if applicable), and Rekor audit (Tier 3).
	Infer(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)

	// GetSession returns the current behavioural profile for a session.
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionState, error)

	// ListSessions streams all active sessions, optionally filtered by tier.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (VyseEngine_ListSessionsClient, error)

	// DeleteSession bans a session and removes its Redis state.
	// Audit records in PostgreSQL are retained.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)

	// GetStats returns aggregate threat statistics.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)

	// HealthCheck returns the engine's internal liveness and readiness status.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type vyseEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewVyseEngineClient(cc grpc.ClientConnInterface) VyseEngineClient {
	return &vyseEngineClient{cc}
}

func (c *vyseEngineClient) Infer(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, VyseEngine_Infer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vyseEngineClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionState, error) {
	out := new(SessionState)
	err := c.cc.Invoke(ctx, VyseEngine_GetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vyseEngineClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (VyseEngine_ListSessionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VyseEngine_ServiceDesc.Streams[0], VyseEngine_ListSessions_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &vyseEngineListSessionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VyseEngine_ListSessionsClient interface {
	Recv() (*SessionState, error)
	grpc.ClientStream
}

type vyseEngineListSessionsClient struct {
	grpc.ClientStream
}

func (x *vyseEngineListSessionsClient) Recv() (*SessionState, error) {
	m := new(SessionState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vyseEngineClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, VyseEngine_DeleteSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vyseEngineClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, VyseEngine_GetStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vyseEngineClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, VyseEngine_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Server
// ─────────────────────────────────────────────────────────────────────────────

// VyseEngineServer is the server API for the VyseEngine service.
// Implemented by engine/src/grpc/service.rs via tonic.
// All implementations must embed UnimplementedVyseEngineServer.
type VyseEngineServer interface {
	Infer(context.Context, *InferenceRequest) (*InferenceResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*SessionState, error)
	ListSessions(*ListSessionsRequest, VyseEngine_ListSessionsServer) error
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedVyseEngineServer()
}

// UnimplementedVyseEngineServer must be embedded to have forward-compatible
// implementations. New RPCs added to vyse.proto in future versions will have
// default unimplemented handlers here, preventing build failures in servers
// that have not yet implemented the new method.
type UnimplementedVyseEngineServer struct{}

func (UnimplementedVyseEngineServer) Infer(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedVyseEngineServer) GetSession(context.Context, *GetSessionRequest) (*SessionState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedVyseEngineServer) ListSessions(*ListSessionsRequest, VyseEngine_ListSessionsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedVyseEngineServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedVyseEngineServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedVyseEngineServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVyseEngineServer) mustEmbedUnimplementedVyseEngineServer() {}

// UnsafeVyseEngineServer may be embedded to opt out of forward compatibility.
// Use of this interface is not recommended — it breaks when new RPCs are added.
type UnsafeVyseEngineServer interface {
	mustEmbedUnimplementedVyseEngineServer()
}

type VyseEngine_ListSessionsServer interface {
	Send(*SessionState) error
	grpc.ServerStream
}

type vyseEngineListSessionsServer struct {
	grpc.ServerStream
}

func (x *vyseEngineListSessionsServer) Send(m *SessionState) error {
	return x.ServerStream.SendMsg(m)
}

// ─────────────────────────────────────────────────────────────────────────────
// Server registration
// ─────────────────────────────────────────────────────────────────────────────

func RegisterVyseEngineServer(s grpc.ServiceRegistrar, srv VyseEngineServer) {
	s.RegisterService(&VyseEngine_ServiceDesc, srv)
}

func _VyseEngine_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VyseEngineServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VyseEngine_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VyseEngineServer).Infer(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VyseEngine_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VyseEngineServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VyseEngine_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VyseEngineServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VyseEngine_ListSessions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSessionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VyseEngineServer).ListSessions(m, &vyseEngineListSessionsServer{stream})
}

func _VyseEngine_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VyseEngineServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VyseEngine_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VyseEngineServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VyseEngine_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VyseEngineServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VyseEngine_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VyseEngineServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VyseEngine_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VyseEngineServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VyseEngine_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VyseEngineServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VyseEngine_ServiceDesc is the grpc.ServiceDesc for the VyseEngine service.
// It is only intended for direct use with grpc.RegisterService, and not to be
// introspected or modified (even as a copy).
var VyseEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vyse.v1.VyseEngine",
	HandlerType: (*VyseEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Infer",
			Handler:    _VyseEngine_Infer_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _VyseEngine_GetSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _VyseEngine_DeleteSession_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _VyseEngine_GetStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VyseEngine_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListSessions",
			Handler:       _VyseEngine_ListSessions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vyse.proto",
}
